[GOOGLE_ADS]
developerToken = "eCfhMTWQWCUQA2LImrboVA"
loginCustomerId = "8177415982"
linkedCustomerId = "4652169644"
jsonKeyFilePath = "C:/xampp/htdocs/aio/storage/app/google-ads/service-account-key.json"
; use_cloud_identity_for_api_access = true